export const images = {
    "LogoFalarohy": "/images/LogoFalarohy.png",
    "authimage" : "/images/authimage.png",
    "bgContinue" : "/images/bg-continue.png",
    "portraitteacher" : "/images/portrait-teacher.png",
    "LangagePython" : "/images/Langage-Python.png",
    "videonew" : "/images/videonew.png",
    "ImageDefault" : "/images/Photo-Image-Icon.jpg",
    "virtualclassroom" : "/images/virtual-classroom.png",
    "téléchargement" : "/images/téléchargement.png",
    "images__1" : "/images/images__1.png",
    "imagesame" : "/images/imagesame.png",
    "instructorTow" : "/images/rereer.png",
    "qrcode" : "/images/qr-code.svg",
    "applicationdesclinux" : "/images/linux_6124995.png",
    "applicationdescandroid" : "/images/logo_11378763.png",
    "applicationdescpngegg" : "/images/pngegg.png",
    "applicationdescwindows" : "/images/windows_2374606.png",
}